analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - .dart_tool/**
    - .idea/**
    - .pub/**
    - .settings/**
    - tool/**
    - bin/**
    - build/**
    - dist/**

  errors:
    always_declare_return_types: error
    always_put_required_named_parameters_first: error
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    assignment_to_const: error
    assignment_to_final: error
    avoid_empty_else: error
    avoid_init_to_null: error
    avoid_null_checks_in_equality_operators: error
    avoid_return_types_on_setters: error
    avoid_slow_async_io: error
    avoid_unused_constructor_parameters: error
    await_only_futures: error
    camel_case_types: error
    cancel_subscriptions: error
    comment_references: error
    control_flow_in_finally: error
    directives_ordering: error
    empty_catches: error
    empty_constructor_bodies: error
    empty_statements: error
    hash_and_equals: error
    implementation_imports: error
    invalid_assignment: error
    invariant_booleans: error
    iterable_contains_unrelated_type: error
    join_return_with_assignment: error
    library_names: error
    library_prefixes: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: error
    missing_return: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    non_constant_identifier_names: error
    not_enough_required_arguments: error
    only_throw_errors: error
    overridden_fields: error
    package_api_docs: error
    package_names: error
    package_prefixed_library_names: error
    parameter_assignments: error
    prefer_adjacent_string_concatenation: error
    prefer_bool_in_asserts: error
    prefer_conditional_assignment: error
    prefer_const_constructors: error
    prefer_const_constructors_in_immutables: error
    prefer_constructors_over_static_methods: error
    prefer_contains: error
    prefer_final_fields: error
    prefer_foreach: error
    prefer_function_declarations_over_variables: error
    prefer_initializing_formals: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_single_quotes: warning
    prefer_typing_uninitialized_variables: error
    recursive_getters: error
    slash_for_doc_comments: error
    sort_unnamed_constructors_first: error
    super_goes_last: error
    test_types_in_equals: error
    throw_in_finally: error
    type_annotate_public_apis: error
    type_init_formals: error
    undefined_class: error
    undefined_function: error
    undefined_method: error
    unnecessary_getters_setters: error
    unnecessary_lambdas: error
    unnecessary_null_aware_assignments: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_overrides: error
    unnecessary_statements: error
    unnecessary_this: error
    unrelated_type_equality_checks: error
    use_rethrow_when_possible: error
    use_string_buffers: error
    use_to_and_as_if_applicable: error
    valid_regexps: error
    unused_local_variable: error

linter:
  rules:
    - avoid_empty_else
    - avoid_slow_async_io
    - control_flow_in_finally
    - empty_statements
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - throw_in_finally
    - valid_regexps
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_return_types_on_setters
    - avoid_slow_async_io
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - comment_references
    - control_flow_in_finally
    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
    - join_return_with_assignment
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_bool_in_asserts
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_statements
    - unnecessary_this
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_initializing_formals
    - prefer_single_quotes
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps
