analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
  - .dart_tool2/**
  - .dart_tool/**
  - .idea/**
  - .pub/**
  - .settings/**
  - tool/**
  - bin/**
  - build/**
  - dist/**
  - lib/**/*.g.dart

  errors:
    unused_local_variable: error
    invalid_assignment: error
    assignment_to_const: error
    assignment_to_final: error
    missing_return: error
    not_enough_required_arguments: error
    undefined_function: error
    undefined_method: error
    undefined_class: error

linter:
  rules:
  - unnecessary_const
  - unnecessary_new
  - avoid_double_and_int_checks
  - avoid_field_initializers_in_const_classes
  - avoid_js_rounded_ints
  - avoid_private_typedef_functions
  - avoid_relative_lib_imports
  - avoid_renaming_method_parameters
  - avoid_single_cascade_in_expression_statements
  - avoid_types_as_parameter_names
  - file_names
  - null_closures
  - prefer_const_declarations
  - prefer_const_literals_to_create_immutables
  - prefer_generic_function_type_aliases
  - prefer_iterable_whereType
  - void_checks


  - always_declare_return_types
  - always_put_required_named_parameters_first
  - always_require_non_null_named_parameters
  - annotate_overrides
  - avoid_empty_else
  - avoid_init_to_null
  - avoid_null_checks_in_equality_operators
  - avoid_return_types_on_setters
  - avoid_slow_async_io
  - avoid_unused_constructor_parameters
  - await_only_futures
  - camel_case_types
  - cancel_subscriptions
  - comment_references
  - control_flow_in_finally
  - directives_ordering
  - empty_catches
  - empty_constructor_bodies
  - empty_statements
  - hash_and_equals
  - implementation_imports
  - invariant_booleans
  - iterable_contains_unrelated_type
  - join_return_with_assignment
  - library_names
  - library_prefixes
  - list_remove_unrelated_type
  - literal_only_boolean_expressions
  - no_adjacent_strings_in_list
  - no_duplicate_case_values
  - non_constant_identifier_names
  - omit_local_variable_types
  - only_throw_errors
  - overridden_fields
  - package_api_docs
  - package_names
  - package_prefixed_library_names
  - parameter_assignments
  - prefer_adjacent_string_concatenation
  - prefer_bool_in_asserts
  - prefer_collection_literals
  - prefer_conditional_assignment
  - prefer_const_constructors
  - prefer_const_constructors_in_immutables
  - prefer_constructors_over_static_methods
  - prefer_contains
  - prefer_final_fields
  - prefer_final_locals
  - prefer_foreach
  - prefer_function_declarations_over_variables
  - prefer_initializing_formals
  - prefer_is_empty
  - prefer_is_not_empty
  - prefer_single_quotes
  - prefer_typing_uninitialized_variables
  - recursive_getters
  - slash_for_doc_comments
  - sort_unnamed_constructors_first
  - super_goes_last
  - test_types_in_equals
  - throw_in_finally
  - type_annotate_public_apis
  - type_init_formals
  - unnecessary_getters_setters
  - unnecessary_null_aware_assignments
  - unnecessary_null_in_if_null_operators
  - unnecessary_overrides
  - unnecessary_statements
  - unnecessary_this
  - unrelated_type_equality_checks
  - use_rethrow_when_possible
  - use_string_buffers
  - use_to_and_as_if_applicable
  - valid_regexps
