name: server
description: A web server without any additional dependencies.
# version: 1.0.0
# homepage: https://www.example.com
# author: eugene.kot <bunopus@gmail.com>

environment:
  sdk: '>=2.0.0-dev.51.0 <2.0.0'

dependencies:
  json_annotation: ^0.2.4

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.2