name: server
description: A web server without any additional dependencies.
# version: 1.0.0
# homepage: https://www.example.com
# author: eugene.kot <bunopus@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:

#dev_dependencies:

