name: models
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# author: eugene.kot <bunopus@gmail.com>

environment:
  sdk: '>=2.0.0-dev.52.0 <2.0.0'

dependencies:
  json_annotation: ^0.2.4

dev_dependencies:
  build_runner: ^0.8.0
  json_serializable: ^0.5.2