name: web
description: Super simple AngularDart app.
# version: 1.0.0
# homepage: https://www.example.com
# author: eugene.kot <bunopus@gmail.com>

environment:
  sdk: ">=2.0.0-dev.52.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha
  angular_router: ^2.0.0-alpha
  models:
    path: ../models


dev_dependencies:
  build_runner: ^0.8.2
  build_test: ^0.10.1+1
  build_web_compilers: ^0.4.0